#!/usr/bin/env bash
callingDir=$(pwd)
rootDir=$(git rev-parse --show-toplevel)
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $rootDir
sloccount --duplicates --details . 2>/dev/null > /tmp/sloccount.sc

python3 $scriptDir/main.py \
  /tmp/sloccount.sc \
  $rootDir/.gitignore \
  $rootDir/.locignore

rm /tmp/sloccount.sc
